//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolumler
    {
        public int Id { get; set; }
        public int FakulteNo { get; set; }
        public int BolumNo { get; set; }
        public string BolumKodu { get; set; }
        public string BolumAd { get; set; }
        public byte AktifPasif { get; set; }
    }
}
