//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dersler
    {
        public Dersler()
        {
            this.DersKayit = new HashSet<DersKayit>();
            this.MufredatDersler = new HashSet<MufredatDersler>();
        }
    
        public int ID { get; set; }
        public string DersKodu { get; set; }
        public string DersAdi { get; set; }
        public bool Durum { get; set; }
        public Nullable<int> Kredi { get; set; }
    
        public virtual ICollection<DersKayit> DersKayit { get; set; }
        public virtual ICollection<MufredatDersler> MufredatDersler { get; set; }
    }
}
