//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iletisim
    {
        public Iletisim()
        {
            this.Kimlik = new HashSet<Kimlik>();
        }
    
        public int ID { get; set; }
        public string Adres { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Email { get; set; }
        public string GSM { get; set; }
    
        public virtual ICollection<Kimlik> Kimlik { get; set; }
    }
}
