//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kimlik
    {
        public Kimlik()
        {
            this.Kullanicilar = new HashSet<Kullanicilar>();
            this.Ogrenci = new HashSet<Ogrenci>();
        }
    
        public int ID { get; set; }
        public string TcNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string DogumYeri { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public int IletisimID { get; set; }
    
        public virtual Iletisim Iletisim { get; set; }
        public virtual ICollection<Kullanicilar> Kullanicilar { get; set; }
        public virtual ICollection<Ogrenci> Ogrenci { get; set; }
    }
}
