//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OBSDbEntities : DbContext
    {
        public OBSDbEntities()
            : base("name=OBSDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DersKayit> DersKayit { get; set; }
        public DbSet<Dersler> Dersler { get; set; }
        public DbSet<Iletisim> Iletisim { get; set; }
        public DbSet<Kimlik> Kimlik { get; set; }
        public DbSet<Kullanicilar> Kullanicilar { get; set; }
        public DbSet<Mufredat> Mufredat { get; set; }
        public DbSet<MufredatDersler> MufredatDersler { get; set; }
        public DbSet<Ogrenci> Ogrenci { get; set; }
        public DbSet<Bolumler> Bolumler { get; set; }
        public DbSet<Fakulteler> Fakulteler { get; set; }
    }
}
