//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        public Ogrenci()
        {
            this.DersKayit = new HashSet<DersKayit>();
        }
    
        public int ID { get; set; }
        public string OgrenciNo { get; set; }
        public int KimlikID { get; set; }
        public int MufredatID { get; set; }
    
        public virtual ICollection<DersKayit> DersKayit { get; set; }
        public virtual Kimlik Kimlik { get; set; }
        public virtual Mufredat Mufredat { get; set; }
    }
}
